--------------------------------------------                  --------------------------------------------------------------------

                                  --->   GROUP BY, HAVING      <---

--------------------------------------------                          -------------------------------------------------------

INSERT INTO STD.STUDENT(ID,FNAME,LNAME,AGE,DEPARTMENT,STD_PERCENTAGE,CITY)VALUES
(1,'GEETHA','SHREE',22,'COMPUTER SCIENCE',82,'PALLIPALAYAM'),
(2,'BRINDHA','SHREE',20,'COMPUTER SCIENCE',85,'ERODE'),
(3,'YAZHINI','KANDASAMY',21,'ARTIFICIAL INTELLIGENCE',82,'ERAYAMANGALAM'),
(4,'DAWOODH','IBRAHIM',20,'COMPUTER SCIENCE',66,'SOLASIRAMANI'),
(5,'GOWRI','SHANKAR',23,'COMPUTER SCIENCE',58,'KUMARAPALAYAM'),
(6,'NETHAJI','SUNDARAM',25,'BIO TECHNOLOGY',77,'TIRUCHENGODE'),
(7,'JAGATHIYA','SATHASIVAM,',20,'INFORMATION TECHNOLOGY',60,'NAMAKKAL'),
(8,'MEGHAA','SRINIVASAN',21,'DATA SCIENCE',72,'ERODE'),
(9,'DURAI','KANNAN',23,'ENGLISH LITERATURE',62,'KARUNGALPALAYAM'),
(10,'BHARATHAN','DURAISAMY',22,'BIO TECHNOLOGY',52,'VATTUR'),
(11,'JENCY','THILAKAVATHI',24,'CHEMISTRY',81,'KAALIPATTI'),
(12,'LAVANYA','BHARATHAN',23,'PHYSICS',89,'PATLUR'),
(13,'SRINITHI','NITHIN',21,'BIO TECHNOLOGY',92,'JEDARPALAYAM'),
(14,'HEMA','DHANASEKAR',22,'INFORMATION TECHNOLOGY',89,'DHARAMPURAM'),
(15,'HARISH','KUMAR',25,'ENGLISH LITERATURE',86,'KANGEYAM'),
(16,'PRIYANKA','THIYAHARAJAN',25,'MATHEMATICS',80,'KALLAKURICHI'),
(17,'KAVITHA','PERUMAL',22,'DATA SCIENCE',72,'GUINDY');

INSERT INTO STD.STUDENT(ID,FNAME,LNAME,AGE,DEPARTMENT,STD_PERCENTAGE,CITY)VALUES
(18,'INDIRA','GANDHI',20,'DATA SCIENCE',85,'GUINDY');

SELECT * FROM STD.STUDENT;

UPDATE STD.STUDENT SET STD_PERCENTAGE=58 WHERE ID=5;

SELECT max(std_percentage) from STD.STUDENT group by STD_PERCENTAGE;        ----> 

SELECT * from STD.STUDENT group by STD_PERCENTAGE;
SELECT max(std_percentage) from STD.STUDENT ;

SELECT max(std_percentage) from STD.STUDENT group by STD_PERCENTAGE; --> 52,58,60,62,72,77...(ascending order la ella datavu vanthu iruku ..how?)
SELECT max(std_percentage) from STD.STUDENT order by ID;             -->  it is not contained in either an aggregate function.. here it have aggrgate fn then y?

SELECT * from STD.STUDENT group by STD_PERCENTAGE;   -->  it is not contained in either an aggregate function... 
SELECT * from STD.STUDENT order by STD_PERCENTAGE;

select * from std.STUDENT;

select max(age) from std.STUDENT;


SELECT * from STD.STUDENT order by 3,7,4;  ---> in city how patlur comes first..and age itself not in ascen order (y)

SELECT MAX(AGE),FNAME,LNAME FROM STD.STUDENT GROUP BY AGE,FNAME,LNAME;

SELECT MAX(AGE),FNAME,LNAME FROM STD.STUDENT ORDER BY AGE,FNAME,LNAME;


SELECT COUNT(LNAME),FNAME,LNAME FROM STD.STUDENT GROUP BY FNAME,LNAME;   --> IN LAST NAME HERE SHREE HAS 2 BUT ITS RETURN AS 1..(Y ?)

SELECT COUNT(LNAME),FNAME,LNAME FROM STD.STUDENT GROUP BY FNAME,LNAME ORDER  BY FNAME;

SELECT FNAME,LNAME FROM STD.STUDENT GROUP BY FNAME 

SELECT MAX(STD_PERCENTAGE) MARK,ID,FNAME,LNAME FROM STD.STUDENT GROUP BY STD_PERCENTAGE,ID,FNAME,LNAME ORDER BY ID HAVING COUNT(ID)>1;
                       
					                                                                                  ------> 
SELECT MAX(STD_PERCENTAGE) MARK,ID,FNAME,LNAME FROM STD.STUDENT GROUP BY STD_PERCENTAGE,ID,FNAME,LNAME HAVING COUNT(*)>1;

SELECT COUNT(*) FROM STD_STUDENT IN (SELECT  STD_PERCENTAGE FROM STD.STUDENT) GROUP BY STD_PERCENTAGE HAVING COUNT(*)>1;