ALTER PROC spDeptWise_Count_IdAge
@V_DEPARTMENT VARCHAR(25) OUTPUT
AS
BEGIN
     SELECT COUNT(ID)  AS NUMBER_OF_STUDENT,
	        COUNT(AGE) AS COUNT_SAME_AGE_CATEGORY
			FROM STD.STUDENT 
			WHERE DEPARTMENT=@V_DEPARTMENT ;

	SELECT DEPARTMENT,
            COUNT (ID)  AS NUMBER_OF_STUDENT,
	        COUNT (AGE) AS COUNT_SAME_AGE_CATEGORY 
			FROM  STD.STUDENT 
			GROUP BY DEPARTMENT;

	 SELECT * FROM 
	        STD.STUDENT WHERE 
			DEPARTMENT=@V_DEPARTMENT ;

END;
GO

     --------------          EXECUTE           -------------------

EXEC spDeptWise_Count_IdAge @V_DEPARTMENT='COMPUTER SCIENCE';


EXEC spDeptWise_Count_IdAge 'COMPUTER SCIENCE';

--EXEC spDeptWise_Count_IdAge @V_DEPARTMENT='BIO TECHNOLOGY';

------------------------------------------------------------------  SELECT QUERY   --------------------------------------------------------------
            SELECT DEPARTMENT COUNT(ID)AS NUMBER_OF_STUDENT,
	        COUNT(AGE) AS COUNT_SAME_AGE_CATEGORY 
			FROM STD.STUDENT 
			WHERE DEPARTMENT='COMPUTER SCIENCE' ;

            SELECT DEPARTMENT,
            COUNT (ID)  AS NUMBER_OF_STUDENT,
	        COUNT (AGE) AS COUNT_SAME_AGE_CATEGORY 
			FROM  STD.STUDENT 
			GROUP BY DEPARTMENT;
			---WHERE DEPARTMENT='COMPUTER SCIENCE' ;

            SELECT FNAME,
            COUNT (ID)  AS NUMBER_OF_STUDENT,
	        COUNT (AGE) AS COUNT_SAME_AGE_CATEGORY 
			FROM   STD.STUDENT 
			GROUP  BY FNAME;

SELECT * FROM STD.STUDENT;