ALTER PROC sp_college
AS
BEGIN
      /* 
	  SELECT AGE,DEPARTMENT,
       COUNT(DEPARTMENT) 
       FROM STD.STUDENT 
       GROUP BY DEPARTMENT,AGE 
       HAVING COUNT(AGE)>=1;
	   */
	   
	   
       SELECT DEPARTMENT,AGE,STD_PERCENTAGE 
	   FROM STD.STUDENT 
	   ORDER BY STD_PERCENTAGE;

       SELECT DEPARTMENT,
       COUNT(DEPARTMENT)DEPARTMENT_COUNT 
       FROM STD.STUDENT 
       GROUP BY DEPARTMENT;

	   /* SELECT AGE,
       COUNT(DEPARTMENT) 
       FROM STD.STUDENT 
       GROUP BY AGE;  */

	   SELECT COUNT(AGE)PEOPLE_IN_SAME_AGE,AGE
	   FROM STD.STUDENT 
	   GROUP BY AGE;

	   SELECT DEPARTMENT,
       COUNT (DEPARTMENT)PEOPLE_IN_SAME_DEPT,
       COUNT (AGE)PEOPLE_IN_SAME_AGE 
       FROM  STD.STUDENT 
       GROUP  BY DEPARTMENT;
END;
GO

EXEC  sp_college;


SELECT * FROM STD.STUDENT;

SELECT * FROM STD.STUDENT
WHERE ID BETWEEN 500 AND 1000 IN
(SELECT AGE,DEPARTMENT,
COUNT(DEPARTMENT) FROM STD.STUDENT 
GROUP BY DEPARTMENT,AGE 
HAVING COUNT(AGE)>1 
ORDER BY ID);

--(list_price) BETWEEN 500 AND 1000; USING IN WHERE CLAUSE

SELECT AGE,DEPARTMENT,
COUNT(DEPARTMENT)NMR_STUDENTS_IN_SAME_DEPT 
FROM STD.STUDENT 
GROUP BY DEPARTMENT,AGE 
HAVING COUNT(AGE)>=1;

SELECT AGE,
COUNT(AGE)MEMBERS_AT_SAME_AGE
FROM STD.STUDENT
GROUP BY AGE;

SELECT DEPARTMENT,AGE,STD_PERCENTAGE 
FROM STD.STUDENT 
GROUP BY DEPARTMENT,AGE,STD_PERCENTAGE
HAVING COUNT(STD_PERCENTAGE)>=1 
ORDER BY STD_PERCENTAGE;

SELECT DEPARTMENT,
COUNT(DEPARTMENT),AGE
FROM STD.STUDENT
GROUP BY DEPARTMENT,AGE
HAVING COUNT(DEPARTMENT)>=1 
ORDER BY DEPARTMENT; 

SELECT DEPARTMENT,
AGE,STD_PERCENTAGE 
FROM STD.STUDENT 
ORDER BY DEPARTMENT;


SELECT DEPARTMENT,
AGE,STD_PERCENTAGE
FROM  STD.STUDENT 
GROUP BY DEPARTMENT,AGE,STD_PERCENTAGE 
HAVING COUNT(STD_PERCENTAGE)>=1 
ORDER BY DEPARTMENT;  ---> ENAKU INTHA DEPT LA ETHANA PERU PADIKIRANGA NU THERIYANYU..?(HOW MANY OF THEM STUDYING IN THIS PARTICULAR DEPT)

SELECT DEPARTMENT,FNAME,
COUNT (DEPARTMENT)PEOPLE_IN_SAME_DEPT,
COUNT (AGE)PEOPLE_IN_SAME_AGE 
FROM  STD.STUDENT 
GROUP  BY DEPARTMENT,FNAME;  -----> Y ITS COMING LIKE THIS

--- HERE IT DOES NOT SHOW THE NUMBER OF PEOPLE STUDING IN THE SAME DEPARTMENT(Y)

SELECT DEPARTMENT,
COUNT (DEPARTMENT)PEOPLE_IN_SAME_DEPT,
COUNT (AGE)PEOPLE_IN_SAME_AGE 
FROM  STD.STUDENT 
GROUP  BY DEPARTMENT; 

SELECT COUNT(AGE)PEOPLE_IN_SAME_AGE,AGE 
FROM STD.STUDENT 
GROUP BY AGE;

SELECT AGE,DEPARTMENT,
COUNT(DEPARTMENT) 
FROM STD.STUDENT 
GROUP BY DEPARTMENT,AGE 
HAVING COUNT(AGE)>=1;

SELECT AGE,DEPARTMENT,
COUNT(DEPARTMENT) 
FROM STD.STUDENT 
GROUP BY DEPARTMENT,AGE    --------------??????????y count i use it
HAVING COUNT(AGE)>=1;

SELECT AGE,
COUNT(DEPARTMENT)SameAgeCategoryInTheDepartment 
FROM STD.STUDENT 
GROUP BY AGE;

SELECT DEPARTMENT,AGE,
COUNT(STD_PERCENTAGE)SAME_MARK    --> HERE IT SHOWS THE RESULT FOR SAME_MARKS  89 AS TWICE
FROM STD.STUDENT
GROUP BY DEPARTMENT,AGE
ORDER BY DEPARTMENT;

SELECT DEPARTMENT,AGE,STD_PERCENTAGE 
FROM STD.STUDENT 
ORDER BY STD_PERCENTAGE;

SELECT DEPARTMENT,AGE,STD_PERCENTAGE,
COUNT(STD_PERCENTAGE) 
FROM STD.STUDENT
GROUP BY DEPARTMENT,AGE,STD_PERCENTAGE
HAVING COUNT(STD_PERCENTAGE)>=1
ORDER BY STD_PERCENTAGE;

SELECT DEPARTMENT,AGE,STD_PERCENTAGE,
COUNT(STD_PERCENTAGE)SAME_MARK 
FROM STD.STUDENT
GROUP BY DEPARTMENT,AGE,STD_PERCENTAGE  --> Y HERE ITSELF DOES NOT SHOE THE SAME MARK AS 2 FOR 89
HAVING COUNT(STD_PERCENTAGE)>=1;

SELECT AGE,
COUNT(STD_PERCENTAGE)SAME_MARKS,STD_PERCENTAGE
FROM STD.STUDENT 
GROUP BY STD_PERCENTAGE,AGE 
ORDER BY 3;  ---> HERE ITSELF 89 PRESENT IN TWICE BUT IT DOES NOT DISPLAY IN SAME_MARKS AS 2 

SELECT COUNT(STD_PERCENTAGE)SAME_MARKS,STD_PERCENTAGE
FROM STD.STUDENT 
GROUP BY STD_PERCENTAGE 
ORDER BY 2;--> IT DOES NOT RESPOND FOR THE ORDER NUMBER(Y)