-- UNION,CONSTRAINTS, INDEX,JOINS(WANT TO LEARN)/ PROCEDURE-?
-- SUBSTRING
--- HOW TO UPADTE MULTIPLE COLUMN

/*
--UNION--

SELECT 'Customer' AS Type, ContactName, City, Country
FROM Customers
UNION
SELECT 'Supplier', ContactName, City, Country
FROM Suppliers;

ABOVE QUERY CONCEPT IS CONFUSING 

1)Find the difference between the total number of CITY entries in the table and
the number of distinct CITY entries in the table.

 */

 SELECT * FROM EMPDATA
 SELECT * FROM SPORT 

 ALTER TABLE SPORT  ADD CITY VARCHAR(50);
 
 ALTER TABLE EMPDATA  ADD CITY VARCHAR(50);


 UPDATE EMPDATA SET CITY=
 CASE EID 
 WHEN 101 THEN 'ERAYAMANGALAM'
 WHEN 102 THEN 'SOLASIRAMANI'
 WHEN 103 THEN 'PALLIPALAYAM'
 WHEN 104 THEN 'TIRUCHENGODE'
 WHEN 105 THEN 'JEDARPALAYAM'
 END
 WHERE EID IN(101,102,103,104,105);

 update sport set city=
 case id 
 when 101 then 'Erayamangalam'
 when 102 then 'Solasiramani'
 when 103 then 'Rasipuram'
 when 104 then 'Tiruchengode'
 when 105 then 'Kokkarayanpettai'
 end
 where id in(101,102,103,104,105);

 ALTER TABLE SPORT ADD DISTRICT VARCHAR(52)
 
 ALTER TABLE EMPDATA ADD DISTRICT VARCHAR(52)

 update sport set city=
 case id 
 when 101 then 'Erayamangalam'
 when 102 then 'Solasiramani'
 when 103 then 'Rasipuram'
 when 104 then 'Tiruchengode'
 when 105 then 'Kokkarayanpettai'
 end
 where id in(101,102,103,104,105);

 update sport set DISTRICT=
 case id 
 when 101 then 'Erode'
 when 102 then 'Namakkal'
 when 103 then 'Dharmapuri'
 when 104 then 'Kanchipuram'
 when 105 then 'Kallakurichi'
 end
 where id in(101,102,103,104,105);

 SELECT * FROM EMPDATA
 SELECT * FROM SPORT 

UPDATE EMPDATA SET DISTRICT=
 CASE EID 
 WHEN 101 THEN 'ERODE'
 WHEN 102 THEN 'NAMAKKAL'
 WHEN 103 THEN 'DHARMAPURI'
 WHEN 104 THEN 'KANCHIPURAM'
 WHEN 105 THEN 'CUDDALORE'
 END
 WHERE EID IN(101,102,103,104,105); 

 SELECT AGE FROM SPORT UNION SELECT AGE FROM EMPDATA  -- 
 SELECT * FROM EMPDATA
 SELECT * FROM SPORT 

 SELECT CITY FROM SPORT
 UNION 
 SELECT CITY FROM EMPDATA 
 ORDER BY CITY; 

 SELECT CITY FROM SPORT
 UNION ALL 
 SELECT CITY FROM EMPDATA 
 ORDER BY CITY; 

 SELECT ID FROM SPORT UNION SELECT EID FROM EMPDATA  

 SELECT ID FROM SPORT UNION ALL SELECT EID FROM EMPDATA  

 SELECT * FROM EMPDATA
 SELECT * FROM SPORT 

 SELECT FNAME,LNAME,AGE,CITY,DISTRICT FROM EMPDATA UNION 
 SELECT FNAME,LNAME,AGE,CITY,DISTRICT FROM SPORT ORDER BY FNAME

 SELECT FNAME,LNAME,AGE,CITY,DISTRICT FROM EMPDATA UNION ALL 
 SELECT FNAME,LNAME,AGE,CITY,DISTRICT FROM SPORT  ORDER BY FNAME       -- HERE UNION AND UNION ALL PROVIDING SAME OUTPUT(HOW ND Y?)

SELECT 'CUSTOMER' AS TYPE, FNAME, CITY, DISTRICT
FROM SPORT
UNION
SELECT 'SUPPLIER', FNAME, CITY, DISTRICT
FROM EMPDATA;

--CONSTRAINTS--

CREATE TABLE Orders (
    OrderID int NOT NULL PRIMARY KEY,
    OrderNumber int NOT NULL,
    PersonID int FOREIGN KEY REFERENCES EMPDATA(EID)             --- PERSON ID IS FOREIGN KEY.. 
	--THIS ID IS TAKEN FROM (EMPDATA) TABLE .. VERA 1 TABLE LA IRUKA DATA(COLUMN AH) CURRENT 
	--TABLE KOODA LINK PANNA INTHA FOREIGN KEY HEPL PANNUTHU....
);
INSERT INTO ORDERS (OrderID,OrderNumber,PersonID)VALUES
(1,77895,3),
(2,44678,3),
(3,22456,2),
(4,24562,1);

/*Msg 547, Level 16, State 0, Line 126
The INSERT statement conflicted with the FOREIGN KEY constraint "FK__Orders__PersonID__75A278F5". The conflict occurred in database "Employee", table "dbo.EMPDATA", column 'EID'.
The statement has been terminated.*/ -- ERROR FRO THE ABOVE QUERY

INSERT INTO ORDERS (OrderID,OrderNumber)VALUES
(1,77895),
(2,44678),
(3,22456),
(4,24562);

/* https://stackoverflow.com/questions/68240628/insert-data-into-a-table-with-a-foreign-key-sql */-- FOREIGN KEY REFERENCE

SELECT * FROM ORDERS;  --- HERE ITSELF ORDERID,ORDERNUMBER HAS ADDED IN THE OUTPUT BUT HOW TO ADD THE PERSONID (?)
SELECT * FROM EMPDATA
